name: KBase Sketch Service test

on:
  pull_request:
    types:
    - opened
    - reopened
    - synchronize
    - ready_for_review
  push:
    # run workflow when merging to main or develop
    branches:
      - main
      - master
      - develop

jobs:
  sketch_service_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Repo checkout
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9.19

      - name: Install dependencies and set up test config
        env:
          TEST_TOKEN: ${{secrets.KBASE_CI_TOKEN}}
        run: |

          # install python libraries
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r dev-requirements.txt

          # set up test config
          cp -n .env.example .env
          sed -i "s#^KBASE_SECURE_CONFIG_PARAM_service_token=.*#KBASE_SECURE_CONFIG_PARAM_service_token=$TEST_TOKEN#" .env

      - name: Run tests
        shell: bash
        run: |
          docker compose up -d
          docker compose run web test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
